config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    get 'home/index'
    resources :posts

    root 'static_pages#home'
    get 'static_pages/info', as: "info"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/users", to: "users#index"
    resources :users
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :courses, only: [:create, :destroy]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(:course_registration_system), root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(:home), root_url %></li>
        <li><%= link_to t(:info), info_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(:users), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
              <%= t(:acccount) %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(:profile), current_user %></li>
              <li><%= link_to t(:settings), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t(:log_out), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(:log_in), login_path %></li>
        <% end %>
        <li><%= link_to "en", locale: :en %></li>
        <li><%= link_to "my", locale: :my %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>